#!/bin/bash

### BEGIN INIT INFO
# Provides:          flyzy2005.com
# Required-Start:    $network $syslog
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ss start
# Description:       ss start
### END INIT INFO
ssserver -c /etc/shadowsocks.json -d start
